src/Entity/Agent.php
<?php

namespace App\Entity;

use App\Repository\AgentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AgentRepository::class)
 */
class Agent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $identification_code;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $lastname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\ManyToOne(targetEntity=Nationality::class, inversedBy="agents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nationality;

    /**
     * @ORM\ManyToMany(targetEntity=Speciality::class, inversedBy="agents")
     */
    private $speciality;

    /**
     * @ORM\ManyToMany(targetEntity=Mission::class, mappedBy="agent")
     */
    private $missions;

    
    public function __construct()
    {
        $this->speciality = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdentificationCode(): ?int
    {
        return $this->identification_code;
    }

    public function setIdentificationCode(int $identification_code): self
    {
        $this->identification_code = $identification_code;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getNationality(): ?Nationality
    {
        return $this->nationality;
    }

    public function setNationality(?Nationality $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function __toString()
    {
        $nb_spe = $this->speciality->count();
        $data_spe = [];
        for($i = 0; $i < $nb_spe; $i++) {
            $data_spe[$i] = $this->getSpeciality()->get($i)->getName();
        }
        return $this->firstname.' '.$this->lastname.' '.$this
            ->nationality->getCountry().' '.implode(' ', $data_spe);
    }

    /**
     * @return Collection|Speciality[]
     */
    public function getSpeciality(): Collection
    {
        return $this->speciality;
    }

    public function addSpeciality(Speciality $speciality): self
    {
        if (!$this->speciality->contains($speciality)) {
            $this->speciality[] = $speciality;
        }

        return $this;
    }

    public function removeSpeciality(Speciality $speciality): self
    {
        $this->speciality->removeElement($speciality);

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->addAgent($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeAgent($this);
        }

        return $this;
    }

}

src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MissionRepository::class)
 * @ORM\Table(name="mission", indexes={@ORM\Index(columns={"title", "description", "code_name", "type"}, flags={"fulltext"})})
 */
class Mission
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $code_name;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $type;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=Nationality::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nationality;

    /**
     * @ORM\ManyToOne(targetEntity=Statute::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $statute;

    /**
     * @ORM\ManyToOne(targetEntity=Speciality::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $speciality;

    /**
     * @ORM\ManyToMany(targetEntity=Agent::class, inversedBy="missions")
     */
    private $agent;

    /**
     * @ORM\ManyToMany(targetEntity=Contact::class, inversedBy="missions")
     */
    private $contact;

    /**
     * @ORM\ManyToMany(targetEntity=Hideout::class, inversedBy="missions")
     */
    private $hideout;

    /**
     * @ORM\ManyToMany(targetEntity=Target::class, inversedBy="missions")
     */
    private $target;


    public function __construct()
    {
        $this->agent = new ArrayCollection();
        $this->contact = new ArrayCollection();
        $this->hideout = new ArrayCollection();
        $this->target = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCodeName(): ?string
    {
        return $this->code_name;
    }

    public function setCodeName(string $code_name): self
    {
        $this->code_name = $code_name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getNationality(): ?Nationality
    {
        return $this->nationality;
    }

    public function setNationality(?Nationality $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getStatute(): ?Statute
    {
        return $this->statute;
    }

    public function setStatute(?Statute $statute): self
    {
        $this->statute = $statute;

        return $this;
    }

    public function getSpeciality(): ?Speciality
    {
        return $this->speciality;
    }

    public function setSpeciality(?Speciality $speciality): self
    {
        $this->speciality = $speciality;

        return $this;
    }

    /**
     * @return Collection|Agent[]
     */
    public function getAgent(): Collection
    {
        return $this->agent;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agent->contains($agent)) {
            $this->agent[] = $agent;
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        $this->agent->removeElement($agent);

        return $this;
    }

    public function __toString(): string
    {
        return $this->id;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContact(): Collection
    {
        return $this->contact;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contact->contains($contact)) {
            $this->contact[] = $contact;
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        $this->contact->removeElement($contact);

        return $this;
    }

    /**
     * @return Collection|Hideout[]
     */
    public function getHideout(): Collection
    {
        return $this->hideout;
    }

    public function addHideout(Hideout $hideout): self
    {
        if (!$this->hideout->contains($hideout)) {
            $this->hideout[] = $hideout;
        }

        return $this;
    }

    public function removeHideout(Hideout $hideout): self
    {
        $this->hideout->removeElement($hideout);

        return $this;
    }

    /**
     * @return Collection|Target[]
     */
    public function getTarget(): Collection
    {
        return $this->target;
    }

    public function addTarget(Target $target): self
    {
        if (!$this->target->contains($target)) {
            $this->target[] = $target;
        }

        return $this;
    }

    public function removeTarget(Target $target): self
    {
        $this->target->removeElement($target);

        return $this;
    }

}

src/Entity/Nationality.php
<?php

namespace App\Entity;

use App\Repository\NationalityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NationalityRepository::class)
 */
class Nationality
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Agent::class, mappedBy="nationality")
     */
    private $agents;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="nationality")
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Target::class, mappedBy="nationality")
     */
    private $targets;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $Country;

    /**
     * @ORM\OneToMany(targetEntity=Hideout::class, mappedBy="nationality")
     */
    private $hideouts;

    /**
     * @ORM\OneToMany(targetEntity=Mission::class, mappedBy="nationality")
     */
    private $missions;

    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->targets = new ArrayCollection();
        $this->hideouts = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Agent[]
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents[] = $agent;
            $agent->setNationality($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getNationality() === $this) {
                $agent->setNationality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setNationality($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getNationality() === $this) {
                $contact->setNationality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Target[]
     */
    public function getTargets(): Collection
    {
        return $this->targets;
    }

    public function addTarget(Target $target): self
    {
        if (!$this->targets->contains($target)) {
            $this->targets[] = $target;
            $target->setNationality($this);
        }

        return $this;
    }

    public function removeTarget(Target $target): self
    {
        if ($this->targets->removeElement($target)) {
            // set the owning side to null (unless already changed)
            if ($target->getNationality() === $this) {
                $target->setNationality(null);
            }
        }

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    /**
     * @return Collection|Hideout[]
     */
    public function getHideouts(): Collection
    {
        return $this->hideouts;
    }

    public function addHideout(Hideout $hideout): self
    {
        if (!$this->hideouts->contains($hideout)) {
            $this->hideouts[] = $hideout;
            $hideout->setNationality($this);
        }

        return $this;
    }

    public function removeHideout(Hideout $hideout): self
    {
        if ($this->hideouts->removeElement($hideout)) {
            // set the owning side to null (unless already changed)
            if ($hideout->getNationality() === $this) {
                $hideout->setNationality(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Mission[]
     */
    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions[] = $mission;
            $mission->setNationality($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            // set the owning side to null (unless already changed)
            if ($mission->getNationality() === $this) {
                $mission->setNationality(null);
            }
        }

        return $this;
    }
}

src/Controller/MissionController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Form\MissionSearchType;
use App\Repository\MissionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;

class MissionController extends AbstractController
{

    /**
     * @Route("/mission", name="mission")
     */
    public function missionsPage(Request $request, PaginatorInterface $paginator, MissionRepository $missionRepository): Response
    {
        $data = $this->getDoctrine()->getRepository(Mission::class)->findAll();
        $form = $this->createForm(MissionSearchType::class);
        $search = $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $missionRepository->searchMissionByWords(
                $search->get('words')->getData(),
                $search->get('statute')->getData(),
                $search->get('nationality')->getData()
            );
        }
        
        $missions = $paginator->paginate(
            $data,
            $request->query->getInt('page', 1),
            12
        );

        return $this->render('mission/index.html.twig', [
            'missions' => $missions,
            'searchForm' => $form->createView()
            ]);
    }

    /**
     * @Route("/mission/edit/{id}", name="mission_edit")
     */
    public function editMission(Mission $mission): Response
    {
        return $this->render('mission/edit.html.twig', [
            'mission' => $mission
            ]);
    }
}

templates/mission/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos missions - Russian KGB{% endblock %}

{% block body %}
	<!-- Heading -->
	<div id="heading">
		<h1>Nos missions</h1>
	</div>

	<!-- Main -->
	<section id="main" class="wrapper">
		<div class="inner">
			<header class="special">
				<h3 style="text-align:center">Комитет государственной безопасности</h3>
			</header>
			<div class="content">
				<div class="row">
					<div class="col-12" style="margin-bottom: 2rem">
						<h2 class="table-title icon fa-caret-right">&nbsp;Mission : {{ mission.title }}</h2>
					</div>
				</div>
				<div class="row">
					<div class="col-6 col-12-medium">
						<h3>Statut de la mission : {{ mission.statute.name }} <span class="statute-color" style="background-color: {{ mission.statute.color }}"></span></h3>
						<div class="table-wrapper">
							<table class="alt" style="margin-bottom: 2rem!important">
								<tbody>
									<tr>
										<td>Nom de code :</td>
										<td>{{ mission.codeName }}</td>
									</tr>
									<tr>
										<td>Type :</td>
										<td>{{ mission.type }}</td>
									</tr>
									<tr>
										<td>Spécialité requise :</td>
										<td>{{ mission.speciality.name }}</td>
									</tr>
									<tr>
										<td>Période :</td>
										<td>Du {{ mission.startDate|date('d/m/Y') }} au {{ mission.endDate|date('d/m/Y') }}</td>
									</tr>
									<tr>
										<td>Pays de localisation :</td>
										<td>{{ mission.nationality.country }}</td>
									</tr>
								</tbody>
							</table>
						</div>
						<h3>Description</h3>
						<blockquote>{{ mission.description }}</blockquote>
						<div class="logo-kgb" style="height:300px"></div>
					</div>
					<div class="col-6 col-12-medium">
						<h3>Les contacts ({{ mission.contact|length }})</h3>
						<table style="margin-bottom: 2rem!important">
							<thead>
								<tr>
									<th>Prénom</th>
									<th>Nom</th>
									<th>Né le</th>
								</tr>
							</thead>
							<tbody>
								{% for contact in mission.contact %}
									<tr>
										<td>{{ contact.firstname }}</td>
										<td>{{ contact.lastname }}</td>
										<td>{{ contact.dateOfBirth|date('d/m/Y') }}</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="3">Il n'y pas encore de contact pour cette mission</td>
									</tr>
									
								{% endfor %}
							</tbody>
						</table>
						<h3>Les planques ({{ mission.hideout|length }})</h3>
						<table style="margin-bottom: 2rem!important">
							<thead>
								<tr>
									<th>Code</th>
									<th>Type</th>
									<th>Adresse</th>
								</tr>
							</thead>
							<tbody>
								{% for hideout in mission.hideout %}
									<tr>
										<td>{{ hideout.code }}</td>
										<td>{{ hideout.type }}</td>
										<td>{{ hideout.address }}</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="3">Il n'y pas encore de planque pour cette mission</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						<h3>Les agents ({{ mission.agent|length }})</h3>
						<table style="margin-bottom: 2rem!important">
							<thead>
								<tr>
									<th>Prénom</th>
									<th>Nom</th>
									<th>Spécialité(s)</th>
								</tr>
							</thead>
							<tbody>
								{% for agent in mission.agent %}
									<tr>
										<td>{{ agent.firstname }}</td>
										<td>{{ agent.lastname }}</td>
										<td>
											{% for speciality in agent.speciality %}
												{{ speciality }}<br>
											{% else %}
												Il aucune spécialité pour cet agent
											{% endfor %}
										</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="3">Il n'y pas encore d'agent pour cette mission</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						<h3>Les cibles ({{ mission.target|length }})</h3>
						<table style="margin-bottom: 2rem!important">
							<thead>
								<tr>
									<th>Prénom</th>
									<th>Nom</th>
									<th>Pays</th>
								</tr>
							</thead>
							<tbody>
								{% for target in mission.target %}
									<tr>
										<td>{{ target.firstname }}</td>
										<td>{{ target.lastname }}</td>
										<td>{{ target.nationality.country }}</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="3">Il n'y pas encore de cible pour cette mission</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
						<a href="{{ path('mission') }}" class="button icon fa-backward" style="float:right">Retour liste</a>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/mission/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos missions - Russian KGB{% endblock %}

{% block body %}
	<!-- Heading -->
	<div id="heading">
		<h1>Nos missions</h1>
	</div>

	<!-- Main -->
	<section id="main" class="wrapper">
		<div class="inner">
			<div class="content" style="padding-bottom: 0;">
				<h3 style="text-align:center">Комитет государственной безопасности</h3>
				{{ form_start(searchForm) }}
					<div class="row" style="justify-content: center;">
						<div class="col-3 col-12-small">
							{{ form_row(searchForm.statute) }}
						</div>
						<div class="col-3 col-12-small">
							{{ form_row(searchForm.nationality) }}
						</div>
						<div style="display:flex">
							<div class="col-3 col-12-small">
								{{ form_widget(searchForm.words) }}
							</div>
							<button type="submit" class="button primary icon fa-search" style="font-size: 22px!important;"></button>
						</div>
					</div>
				{{ form_end(searchForm) }}
			</div>
			<div class="highlights">
				{% for mission in missions %}
					<section>
						<div class="content">
							<header>
								<a href="{{ path('mission_edit', {'id': mission.id }) }}" class="{{ 'icon '~mission.speciality.icon }}"><span class="label">Icon</span></a>
								<h3>{{ mission.title }}</h3>
								<h4>Type : {{ mission.type }}</h4>
							</header>
							<p>{{ mission.description|slice(0, 100) }}...</p>
							<p>Du {{ mission.startDate|date('d/m/Y') }} au {{ mission.endDate|date('d/m/Y') }}</p>
							<h4 class="icon fa-map-marker" style="font-size: 1rem;">&nbsp;{{ mission.nationality.country }}</h4>
							<p><span class="statute-color" style="background-color: {{ mission.statute.color }}"></span>&nbsp;{{ mission.statute.name }}</p>
							<a href="{{ path('mission_edit', {'id': mission.id }) }}" class="button primary small" role="button">En savoir plus</a>
						</div>
					</section>
				{% endfor %}
			</div>	
			{% if missions.getTotalItemCount > 8 %}
				<div class="navigation">
					{{ knp_pagination_render(missions) }}
				</div>
			{% endif %}	
		</div>
	</section>
{% endblock %}